---
- name: Install NGINX
  become: yes
  apt:
    name: nginx
    state: present

- name: NGINX vhost config files
  become: yes
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/nginx/sites-available/{{ item }}"
    owner: root
    mode: 0644
    group: root
  loop:
    - default
    - chronograf.beverley-soaring.org.au
    - weather.beverley-soaring.org.au
    - wind.beverley-soaring.org.au

- name: NGINX symlink to sites-enabled
  become: yes
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  loop:
    - default
    - chronograf.beverley-soaring.org.au
    - weather.beverley-soaring.org.au
    - wind.beverley-soaring.org.au

- name: Update hash buckets config
  become: yes
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '# server_names_hash_bucket_size 64;'
    replace: 'server_names_hash_bucket_size 64;'
    validate: 'nginx -t -c %s'

- name: Restart NGINX
  become: yes
  service: 
    name: nginx
    state: restarted
