---
- name: Install InfluxDB Server
  become: yes
  apt: 
    name: influxdb
    state: present

- name: Modify InfluxDB hostname
  become: yes
  replace:
    dest: /etc/influxdb/influxdb.conf
    regexp: 'hostname = "localhost"'
    replace: 'hostname = "{{ ansible_hostname }}"'
    backup: yes

- name: Start the InfluxDB service
  become: yes
  service:
    name: influxdb
    state: restarted
